source_countries: ['brazil', 'india', 'japan', 'nigeria', 'portugal', 'turkey']
source_data_path: ./data/part1
target_country: the United States
prompt: make the image culturally relevant to the United States
seed: 0
image_guidance: 1.5
num_inference_steps: 100
text_guidance: 7.5
debug: False
